// src/pages/QuizzesPage.tsx
import React, { useEffect, useState } from 'react';
import { AlertCircle, Loader2 } from 'lucide-react'; // Ensure Loader2 is imported for loading states
import QuizCard from '../components/quiz/QuizCard';
import QuizFilter from '../components/quiz/QuizFilter';
import Alert from '../components/ui/Alert'; // Assuming you have an Alert component for error display
import { useQuizStore } from '../store/quizStore';
import { QuizFilter as QuizFilterType } from '../types';

const QuizzesPage: React.FC = () => {
  const { quizzes, loading, error, fetchQuizzes } = useQuizStore();
  const [filter, setFilter] = useState<QuizFilterType>({});

  // Initial fetch of quizzes on component mount
  // ⭐ MODIFIED: Always fetch with visibility: 'global' by default ⭐
  useEffect(() => {
    fetchQuizzes({ ...filter, visibility: 'global' });
  }, [fetchQuizzes]); // Depend on fetchQuizzes only, as filter is handled by handleFilterChange

  const handleFilterChange = (newFilter: QuizFilterType) => {
    setFilter(newFilter);
    // ⭐ MODIFIED: Always ensure visibility: 'global' when fetching with filters ⭐
    fetchQuizzes({ ...newFilter, visibility: 'global' });
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="mb-8 flex flex-col sm:flex-row sm:justify-between sm:items-center">
        <div>
          <h1 className="text-3xl font-bold text-slate-800">Global Quizzes</h1>
          {/* ⭐ Updated descriptive text for a Global Quizzes page ⭐ */}
          <p className="text-slate-600 mt-2">
            Explore a wide range of quizzes generated by administrators for everyone to enjoy.
          </p>
        </div>
      </div>

      {/* ⭐ ADDED: hideVisibilityFilter prop to QuizFilter, as this page only shows 'global' ⭐ */}
      {/* We are also hiding the createdBy filter as it's not relevant for global quizzes */}
      <QuizFilter onFilterChange={handleFilterChange} hideVisibilityFilter={true} hideCreatedByFilter={true} />

      {error && (
        // Using your Alert component for consistent error display
        <Alert
          type="error"
          message={error}
          className="mt-4"
          icon={<AlertCircle className="h-5 w-5" />} // Explicitly pass icon if Alert component uses it
        />
      )}

      {loading ? (
        <div className="flex justify-center items-center h-64">
          <Loader2 className="h-12 w-12 animate-spin text-sky-500" /> {/* Using Lucide icon */}
        </div>
      ) : quizzes.length === 0 ? (
        <div className="text-center py-12 bg-white rounded-lg shadow-sm">
          <h3 className="text-lg font-medium text-slate-900 mb-2">No global quizzes found</h3>
          {/* Updated message for no quizzes */}
          <p className="text-slate-500">
            Try changing your filters or check back later for new global quizzes.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {quizzes.map((quiz) => (
            <QuizCard key={quiz.id} quiz={quiz} />
          ))}
        </div>
      )}
    </div>
  );
};

export default QuizzesPage;